CREATE TABLE IF NOT EXISTS public.scopus_val_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stage TEXT NOT NULL,
  data JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.scopus_val_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role_all" ON public.scopus_val_log;
CREATE POLICY "service_role_all" ON public.scopus_val_log
  FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_read" ON public.scopus_val_log;
CREATE POLICY "anon_read" ON public.scopus_val_log
  FOR SELECT TO anon USING (true);
