-- =============================================================
-- Migration: Convert all UUID PKs to BIGINT IDENTITY
-- Idempotent: only converts if columns are still UUID
-- =============================================================

-- 1. Drop all FK constraints
ALTER TABLE public.bancas DROP CONSTRAINT IF EXISTS bancas_discente_id_fkey;
ALTER TABLE public.orientacoes DROP CONSTRAINT IF EXISTS orientacoes_docente_id_fkey;
ALTER TABLE public.orientacoes DROP CONSTRAINT IF EXISTS orientacoes_discente_id_fkey;
ALTER TABLE public.projetos_pesquisa DROP CONSTRAINT IF EXISTS projetos_pesquisa_coordenador_id_fkey;
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_id_fkey;

-- 2. Handle profiles table: add user_id, convert id to BIGINT
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'user_id'
  ) THEN
    ALTER TABLE public.profiles ADD COLUMN user_id UUID;
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'id' AND data_type = 'uuid'
    ) THEN
      UPDATE public.profiles SET user_id = id WHERE id IS NOT NULL;
    END IF;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'id' AND data_type = 'uuid'
  ) THEN
    ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_pkey;
    ALTER TABLE public.profiles DROP COLUMN id;
    ALTER TABLE public.profiles ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
    ALTER TABLE public.profiles ADD PRIMARY KEY (id);
  END IF;
END $$;

ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_user_id_fkey;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_user_id_key;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_user_id_key UNIQUE (user_id);

-- 3. Convert all other table id columns from UUID to BIGINT
DO $$
DECLARE
  tbl TEXT;
BEGIN
  FOR tbl IN SELECT unnest(ARRAY[
    'bancas','discentes','disciplinas','docentes','egressos','eventos',
    'impacto_social','mobilidade_docente','orientacoes','patentes','ppg',
    'premiacoes','producao_tecnica','projetos_pesquisa','publicacoes'
  ])
  LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = tbl AND column_name = 'id' AND data_type = 'uuid'
    ) THEN
      EXECUTE format('ALTER TABLE public.%I DROP CONSTRAINT IF EXISTS %I_pkey', tbl, tbl);
      EXECUTE format('ALTER TABLE public.%I DROP COLUMN id', tbl);
      EXECUTE format('ALTER TABLE public.%I ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY', tbl);
      EXECUTE format('ALTER TABLE public.%I ADD PRIMARY KEY (id)', tbl);
    END IF;
  END LOOP;
END $$;

-- 4. Convert FK columns from UUID to BIGINT
DO $$
DECLARE
  col_rec RECORD;
BEGIN
  FOR col_rec IN
    SELECT table_name, column_name
    FROM information_schema.columns
    WHERE table_schema = 'public' AND data_type = 'uuid'
      AND column_name IN ('discente_id', 'docente_id', 'coordenador_id')
  LOOP
    EXECUTE format('ALTER TABLE public.%I DROP COLUMN %I', col_rec.table_name, col_rec.column_name);
    EXECUTE format('ALTER TABLE public.%I ADD COLUMN %I BIGINT', col_rec.table_name, col_rec.column_name);
  END LOOP;
END $$;

-- 5. Truncate and re-seed (relationships lost during conversion)
TRUNCATE public.bancas, public.discentes, public.disciplinas, public.docentes,
  public.egressos, public.eventos, public.impacto_social, public.mobilidade_docente,
  public.orientacoes, public.patentes, public.ppg, public.premiacoes,
  public.producao_tecnica, public.projetos_pesquisa, public.publicacoes
RESTART IDENTITY;

-- 6. Re-seed data
INSERT INTO public.ppg (nome, modalidade, nivel, uf) VALUES
  ('Engenharia de Sistemas e Processos', 'Acadêmico', 'Mestrado/Doutorado', 'SP');

INSERT INTO public.docentes (nome, scopus_id, indice_h, bolsa_cnpq, jdp, licenca) VALUES
  ('Dr. Carlos Roberto', '123456789', 25, 'PQ 1A', false, ''),
  ('Dra. Aline Mendes', '987654321', 18, 'PQ 2', true, 'Saúde (2 meses)');

INSERT INTO public.discentes (nome, cpf, data_ingresso, status, link_lattes) VALUES
  ('João Pedro Alves', '12345678901', '2024-03-01', 'ativo', 'http://lattes.cnpq.br/1234567890123456'),
  ('Maria Fernanda Costa', '98765432109', '2023-03-01', 'ativo', 'http://lattes.cnpq.br/9876543210987654');

INSERT INTO public.egressos (nome, ano_titulacao, atuacao_profissional, link_lattes) VALUES
  ('Carlos Eduardo Lima', 2024, 'Professor Universitário - UFSC', 'http://lattes.cnpq.br/1111111111111111'),
  ('Ana Paula Souza', 2023, 'Pesquisadora - Embrapa', 'http://lattes.cnpq.br/2222222222222222');

INSERT INTO public.bancas (titulo_trabalho, data, discente_id, membros, tipo) VALUES
  ('Análise de Sistemas Reativos Aplicados à Indústria 4.0', '2025-06-15',
   (SELECT id FROM public.discentes WHERE nome = 'João Pedro Alves'),
   'Dr. Carlos Roberto (Presidente), Dra. Aline Mendes, Dr. Pedro Santos', 'Mestrado'),
  ('Qualificação: Otimização de Polímeros Biodegradáveis', '2025-04-10',
   (SELECT id FROM public.discentes WHERE nome = 'Maria Fernanda Costa'),
   'Dra. Aline Mendes (Presidente), Dr. Carlos Roberto', 'Qualificação');

INSERT INTO public.orientacoes (docente_id, discente_id, tipo, inicio, fim, status) VALUES
  ((SELECT id FROM public.docentes WHERE nome = 'Dr. Carlos Roberto'),
   (SELECT id FROM public.discentes WHERE nome = 'João Pedro Alves'), 'Mestrado', '2024-03', '', 'ativo'),
  ((SELECT id FROM public.docentes WHERE nome = 'Dra. Aline Mendes'),
   (SELECT id FROM public.discentes WHERE nome = 'Maria Fernanda Costa'), 'Doutorado', '2023-03', '', 'ativo');

INSERT INTO public.projetos_pesquisa (titulo, descricao, inicio, fim, coordenador_id, financiamento, orgao_fomento) VALUES
  ('Sistemas Inteligentes para Indústria 4.0', 'Projeto focado no desenvolvimento de sistemas de controle preditivo para processos industriais.', '2024-01', '2027-12',
   (SELECT id FROM public.docentes WHERE nome = 'Dr. Carlos Roberto'), true, 'CNPq'),
  ('Materiais Avançados para Energia Renovável', 'Desenvolvimento de polímeros para células solares de alta eficiência.', '2023-06', '2026-06',
   (SELECT id FROM public.docentes WHERE nome = 'Dra. Aline Mendes'), true, 'FAPESP');

INSERT INTO public.disciplinas (nome, codigo, creditos, ano_semestre) VALUES
  ('Tópicos em Engenharia de Sistemas', 'ESP-501', 4, '2025/1'),
  ('Métodos Numéricos Avançados', 'ESP-502', 4, '2025/1'),
  ('Materiais Funcionais', 'ESP-503', 3, '2025/2');

INSERT INTO public.publicacoes (titulo, autores, periodico, ano, doi, justificativa) VALUES
  ('Otimização de Processos Químicos Industriais', 'Carlos Roberto, João Silva', 'Chemical Engineering Journal', 2025, '10.1016/j.cej.2025', 'Alto impacto na indústria de base.');

INSERT INTO public.mobilidade_docente (tipo, nome, instituicao, periodo, link, modalidade) VALUES
  ('docente', 'Dra. Aline Mendes', 'MIT - USA', '01/2025 a 06/2025', 'https://exemplo.com/doc', 'internacional');

INSERT INTO public.eventos (docente, evento, local_data, papel) VALUES
  ('Dr. Carlos Roberto', 'Congresso Brasileiro de Engenharia', 'São Paulo - Out/2025', 'Coordenador de Comissão Científica');

INSERT INTO public.patentes (titulo, status, autores, inpi) VALUES
  ('Sistema de Controle Reativo de Polímeros', 'Concessão', 'Carlos Roberto, Marcos Souza', 'BR 10 2025 123456 7');

INSERT INTO public.producao_tecnica (titulo, ano, autores, tipo, link_comprovacao) VALUES
  ('Software de Simulação de Processos Químicos - SimProQ', 2025, 'Carlos Roberto, João Silva', 'Software', 'https://exemplo.com/software'),
  ('Relatório Técnico: Análise de Eficiência Energética', 2024, 'Aline Mendes', 'Relatório', 'https://exemplo.com/relatorio');

INSERT INTO public.impacto_social (titulo, descricao, ano, link_comprovacao) VALUES
  ('Programa de Extensão: Ciência nas Escolas', 'Atividades de popularização da ciência em escolas públicas da região.', 2025, 'https://exemplo.com/impacto'),
  ('Consultoria Técnica para Pequenas Indústrias', 'Assessoria técnica para implementação de processos sustentáveis.', 2024, 'https://exemplo.com/consultoria');

INSERT INTO public.premiacoes (titulo, ano, nome_premiado, instituicao) VALUES
  ('Prêmio CAPES de Tese - Engenharias II', 2025, 'Carlos Eduardo Lima', 'CAPES'),
  ('Menção Honrosa - Congresso Brasileiro de Engenharia', 2024, 'João Pedro Alves', 'ABCM');

-- 7. Recreate FK constraints
ALTER TABLE public.bancas ADD CONSTRAINT bancas_discente_id_fkey
  FOREIGN KEY (discente_id) REFERENCES public.discentes(id) ON DELETE SET NULL;
ALTER TABLE public.orientacoes ADD CONSTRAINT orientacoes_docente_id_fkey
  FOREIGN KEY (docente_id) REFERENCES public.docentes(id) ON DELETE SET NULL;
ALTER TABLE public.orientacoes ADD CONSTRAINT orientacoes_discente_id_fkey
  FOREIGN KEY (discente_id) REFERENCES public.discentes(id) ON DELETE SET NULL;
ALTER TABLE public.projetos_pesquisa ADD CONSTRAINT projetos_pesquisa_coordenador_id_fkey
  FOREIGN KEY (coordenador_id) REFERENCES public.docentes(id) ON DELETE SET NULL;

-- 8. Update get_user_role to use user_id
CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS TEXT AS $$
BEGIN
  RETURN COALESCE(
    (SELECT role FROM public.profiles WHERE user_id = auth.uid()),
    'viewer'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 9. Update handle_new_user to use user_id
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (user_id, email, name, role)
  VALUES (NEW.id, NEW.email, COALESCE(NEW.raw_user_meta_data->>'name', ''), 'viewer')
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 10. Ensure existing profiles have correct user_id
UPDATE public.profiles SET user_id = NULL WHERE user_id IS NULL;
