-- Migração para confirmação de coautoria com orientandos/egressos do P²CEM (Norma de Recondução § 4º)
-- Permite vincular publicações a discentes ou egressos confirmados, ou registrar explicitamente 'sem_coautoria'

CREATE TABLE IF NOT EXISTS public.publicacoes_coautores_programa (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publicacao_id BIGINT NOT NULL REFERENCES public.publicacoes(id) ON DELETE CASCADE,
  discente_id BIGINT REFERENCES public.discentes(id) ON DELETE SET NULL,
  egresso_id BIGINT REFERENCES public.egressos(id) ON DELETE SET NULL,
  tipo TEXT NOT NULL DEFAULT 'orientando', -- 'orientando' | 'egresso' | 'sem_coautoria'
  nome_citado TEXT NOT NULL DEFAULT '',
  grau_confianca NUMERIC DEFAULT 1.0,
  confirmado_por TEXT,
  confirmado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT check_publicacoes_coautores_tipo CHECK (tipo IN ('orientando', 'egresso', 'sem_coautoria'))
);

CREATE INDEX IF NOT EXISTS idx_pub_coautores_pub_id ON public.publicacoes_coautores_programa(publicacao_id);
CREATE INDEX IF NOT EXISTS idx_pub_coautores_discente_id ON public.publicacoes_coautores_programa(discente_id);
CREATE INDEX IF NOT EXISTS idx_pub_coautores_egresso_id ON public.publicacoes_coautores_programa(egresso_id);
CREATE INDEX IF NOT EXISTS idx_pub_coautores_tipo ON public.publicacoes_coautores_programa(tipo);

-- Habilita RLS
ALTER TABLE public.publicacoes_coautores_programa ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS idempotentes
DROP POLICY IF EXISTS "publicacoes_coautores_select" ON public.publicacoes_coautores_programa;
CREATE POLICY "publicacoes_coautores_select" ON public.publicacoes_coautores_programa
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "publicacoes_coautores_insert" ON public.publicacoes_coautores_programa;
CREATE POLICY "publicacoes_coautores_insert" ON public.publicacoes_coautores_programa
  FOR INSERT TO authenticated WITH CHECK (
    get_user_role() = ANY (ARRAY['admin'::text, 'editor'::text])
  );

DROP POLICY IF EXISTS "publicacoes_coautores_update" ON public.publicacoes_coautores_programa;
CREATE POLICY "publicacoes_coautores_update" ON public.publicacoes_coautores_programa
  FOR UPDATE TO authenticated
  USING (get_user_role() = ANY (ARRAY['admin'::text, 'editor'::text]))
  WITH CHECK (get_user_role() = ANY (ARRAY['admin'::text, 'editor'::text]));

DROP POLICY IF EXISTS "publicacoes_coautores_delete" ON public.publicacoes_coautores_programa;
CREATE POLICY "publicacoes_coautores_delete" ON public.publicacoes_coautores_programa
  FOR DELETE TO authenticated
  USING (get_user_role() = ANY (ARRAY['admin'::text, 'editor'::text]));
